version: "3.6"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 9117:9117 # jackett
      - 8085:8080 # qbittorrent
      - 6885:6881 # qbittorrent
      - 6885:6881/udp # qbittorrent
    restart: always
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      # Timezone for accurate log times
      - TZ=

  jackett:
    network_mode: "service:gluetun"

  qbittorrent:
    network_mode: "service:gluetun"
